services:
  - type: web
    name: myweddingpage
    env: node
    region: frankfurt
    plan: free
    branch: develop
    buildCommand: |
      # Use Node 20
      nvm install 20
      nvm use 20
      node -v

      # Enable pnpm
      corepack enable
      corepack prepare pnpm@latest --activate

      # Install dependencies & generate Prisma client
      pnpm install --frozen-lockfile
      pnpm prisma generate

      # Build Next.js app
      pnpm build
    startCommand: pnpm start
    envVars:
      - key: DATABASE_URL
        sync: true
      - key: NEXTAUTH_SECRET
        sync: true
      - key: NEXT_PUBLIC_APP_URL
        sync: true
    autoDeploy: true
    disk:
      sizeGB: 2
